modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Meldexun/ReachFix/issues"
[[mods]]
modId="reachfix"
version="${version}"
displayName="Reach Fix"
authors="Meldexun"
description='''
'''
